"""add first_name and last_name to leads

Revision ID: 85fcf7522baa
Revises: 7e803d115780
Create Date: 2025-08-06 15:31:15.387756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fcf7522baa'
down_revision: Union[str, Sequence[str], None] = '7e803d115780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_name')
    op.drop_column('leads', 'first_name')
    # ### end Alembic commands ###
