"""Add chat widget models

Revision ID: 95ee6ff2147a
Revises: h5c6d7e8f9g0
Create Date: 2026-01-31 19:23:01.581816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ee6ff2147a'
down_revision: Union[str, Sequence[str], None] = 'h5c6d7e8f9g0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_widget_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=False),
    sa.Column('services', sa.Text(), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('extra_context', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('widget_position', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_widget_configs_id'), 'chat_widget_configs', ['id'], unique=False)
    op.create_index(op.f('ix_chat_widget_configs_organization_id'), 'chat_widget_configs', ['organization_id'], unique=True)
    op.create_table('chat_widget_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('page_url', sa.String(length=2048), nullable=True),
    sa.Column('lead_email', sa.String(length=255), nullable=True),
    sa.Column('lead_name', sa.String(length=255), nullable=True),
    sa.Column('lead_phone', sa.String(length=50), nullable=True),
    sa.Column('lead_captured_at', sa.DateTime(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens_input', sa.Integer(), nullable=False),
    sa.Column('total_tokens_output', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['chat_widget_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_widget_conversations_config_id'), 'chat_widget_conversations', ['config_id'], unique=False)
    op.create_index(op.f('ix_chat_widget_conversations_id'), 'chat_widget_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_chat_widget_conversations_lead_email'), 'chat_widget_conversations', ['lead_email'], unique=False)
    op.create_index(op.f('ix_chat_widget_conversations_session_id'), 'chat_widget_conversations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_widget_conversations_session_id'), table_name='chat_widget_conversations')
    op.drop_index(op.f('ix_chat_widget_conversations_lead_email'), table_name='chat_widget_conversations')
    op.drop_index(op.f('ix_chat_widget_conversations_id'), table_name='chat_widget_conversations')
    op.drop_index(op.f('ix_chat_widget_conversations_config_id'), table_name='chat_widget_conversations')
    op.drop_table('chat_widget_conversations')
    op.drop_index(op.f('ix_chat_widget_configs_organization_id'), table_name='chat_widget_configs')
    op.drop_index(op.f('ix_chat_widget_configs_id'), table_name='chat_widget_configs')
    op.drop_table('chat_widget_configs')
    # ### end Alembic commands ###
